export const products = [
    // Fresh Produce (8 products)
    {
      image: 'https://ecobacgiang.vn/150?text=Organic+Fruits',
      discount: '-11%',
      name: 'Organic Fruits and Veggies Supplement - Support Diet',
      rating: 5,
      reviews: 35,
      price: 16,
      originalPrice: 22,
      inStock: 'In Stock',
      category: 'Fresh Produce',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Avocado',
      discount: '-20%',
      name: 'Food Huggers Avocado Huggers 2pc Silicone Reusable',
      rating: 5,
      reviews: 19,
      price: 11,
      originalPrice: 13,
      inStock: 'In Stock',
      category: 'Fresh Produce',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Oranges',
      discount: '-10%',
      name: 'Juicy Indian River Florida Navel Oranges Grove Fresh 2 Trays',
      rating: 5,
      reviews: 76,
      price: 59,
      originalPrice: 65,
      inStock: 'In Stock',
      category: 'Fresh Produce',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Spinach',
      discount: '-12%',
      name: 'Fresh Organic Baby Spinach 10oz Pack',
      rating: 4,
      reviews: 31,
      price: 5,
      originalPrice: 6,
      inStock: 'In Stock',
      category: 'Fresh Produce',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Berries',
      discount: '-30%',
      name: 'Mixed Organic Berries 16oz Pack',
      rating: 5,
      reviews: 33,
      price: 9,
      originalPrice: 13,
      inStock: 'In Stock',
      category: 'Fresh Produce',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Apples',
      discount: '-15%',
      name: 'Organic Gala Apples 3lb Bag',
      rating: 4,
      reviews: 28,
      price: 7,
      originalPrice: 8,
      inStock: 'In Stock',
      category: 'Fresh Produce',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Broccoli',
      discount: '-10%',
      name: 'Fresh Organic Broccoli 1lb',
      rating: 5,
      reviews: 22,
      price: 4,
      originalPrice: 5,
      inStock: 'In Stock',
      category: 'Fresh Produce',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Carrots',
      discount: '-18%',
      name: 'Organic Baby Carrots 16oz Pack',
      rating: 4,
      reviews: 30,
      price: 3,
      originalPrice: 4,
      inStock: 'In Stock',
      category: 'Fresh Produce',
    },
  
    // Whole Grains (7 products)
    {
      image: 'https://ecobacgiang.vn/150?text=Oats',
      discount: '-15%',
      name: 'Better Oats Organic Old Fashioned Oats, 16 OZ Tub',
      rating: 5,
      reviews: 18,
      price: 39,
      originalPrice: 46,
      inStock: 'In Stock',
      category: 'Whole Grains',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Quinoa',
      discount: '-18%',
      name: 'Organic Quinoa Grain 2lb Pack',
      rating: 4,
      reviews: 15,
      price: 8,
      originalPrice: 10,
      inStock: 'In Stock',
      category: 'Whole Grains',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Brown+Rice',
      discount: '-12%',
      name: 'Organic Brown Rice 2lb Bag',
      rating: 5,
      reviews: 22,
      price: 6,
      originalPrice: 7,
      inStock: 'In Stock',
      category: 'Whole Grains',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Barley',
      discount: '-10%',
      name: 'Organic Pearl Barley 1lb Pack',
      rating: 4,
      reviews: 19,
      price: 4,
      originalPrice: 5,
      inStock: 'In Stock',
      category: 'Whole Grains',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Bulgur',
      discount: '-15%',
      name: 'Organic Bulgur Wheat 1lb',
      rating: 5,
      reviews: 25,
      price: 5,
      originalPrice: 6,
      inStock: 'In Stock',
      category: 'Whole Grains',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Whole+Grain+1',
      discount: '-10%',
      name: 'Organic Whole Grain Item 1',
      rating: 4,
      reviews: 15,
      price: 4,
      originalPrice: 5,
      inStock: 'In Stock',
      category: 'Whole Grains',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Whole+Grain+2',
      discount: '-11%',
      name: 'Organic Whole Grain Item 2',
      rating: 4,
      reviews: 16,
      price: 5,
      originalPrice: 6,
      inStock: 'In Stock',
      category: 'Whole Grains',
    },
  
    // Lean Protein (8 products)
    {
      image: 'https://ecobacgiang.vn/150?text=Chicken',
      discount: '-40%',
      name: 'Just Bare Natural Fresh Chicken Tenders | No Antibiotics Ever',
      rating: 5,
      reviews: 24,
      price: 149,
      originalPrice: 255,
      inStock: 'In Stock',
      category: 'Lean Protein',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Salmon',
      discount: '-30%',
      name: 'Wild Caught Alaskan Salmon Fillets 12oz',
      rating: 5,
      reviews: 29,
      price: 22,
      originalPrice: 32,
      inStock: 'In Stock',
      category: 'Lean Protein',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Yogurt',
      discount: '-20%',
      name: 'Greek Yogurt Plain 32oz Tub',
      rating: 4,
      reviews: 38,
      price: 6,
      originalPrice: 8,
      inStock: 'In Stock',
      category: 'Lean Protein',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Eggs',
      discount: '-25%',
      name: 'Organic Free-Range Eggs 12 Pack',
      rating: 5,
      reviews: 45,
      price: 4,
      originalPrice: 6,
      inStock: 'In Stock',
      category: 'Lean Protein',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Turkey',
      discount: '-15%',
      name: 'Organic Ground Turkey 1lb',
      rating: 4,
      reviews: 30,
      price: 8,
      originalPrice: 10,
      inStock: 'In Stock',
      category: 'Lean Protein',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Lean+Protein+1',
      discount: '-10%',
      name: 'Organic Lean Protein Item 1',
      rating: 4,
      reviews: 20,
      price: 6,
      originalPrice: 8,
      inStock: 'In Stock',
      category: 'Lean Protein',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Lean+Protein+2',
      discount: '-11%',
      name: 'Organic Lean Protein Item 2',
      rating: 4,
      reviews: 21,
      price: 7,
      originalPrice: 9,
      inStock: 'In Stock',
      category: 'Lean Protein',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Lean+Protein+3',
      discount: '-12%',
      name: 'Organic Lean Protein Item 3',
      rating: 4,
      reviews: 22,
      price: 8,
      originalPrice: 10,
      inStock: 'In Stock',
      category: 'Lean Protein',
    },
  
    // Healthy Fats (7 products)
    {
      image: 'https://ecobacgiang.vn/150?text=Almonds',
      discount: '-25%',
      name: 'Organic Whole Almonds 1lb Bag',
      rating: 4,
      reviews: 42,
      price: 12,
      originalPrice: 16,
      inStock: 'In Stock',
      category: 'Healthy Fats',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Olive+Oil',
      discount: '-22%',
      name: 'Extra Virgin Olive Oil 500ml Bottle',
      rating: 5,
      reviews: 53,
      price: 14,
      originalPrice: 18,
      inStock: 'In Stock',
      category: 'Healthy Fats',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Chia+Seeds',
      discount: '-15%',
      name: 'Organic Chia Seeds 12oz Bag',
      rating: 5,
      reviews: 27,
      price: 7,
      originalPrice: 8,
      inStock: 'In Stock',
      category: 'Healthy Fats',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Walnuts',
      discount: '-10%',
      name: 'Raw Whole Walnuts 1lb Bag',
      rating: 5,
      reviews: 22,
      price: 10,
      originalPrice: 11,
      inStock: 'In Stock',
      category: 'Healthy Fats',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Flaxseeds',
      discount: '-18%',
      name: 'Organic Ground Flaxseeds 12oz',
      rating: 4,
      reviews: 26,
      price: 6,
      originalPrice: 7,
      inStock: 'In Stock',
      category: 'Healthy Fats',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Healthy+Fats+1',
      discount: '-10%',
      name: 'Organic Healthy Fats Item 1',
      rating: 4,
      reviews: 20,
      price: 8,
      originalPrice: 10,
      inStock: 'In Stock',
      category: 'Healthy Fats',
    },
    {
      image: 'https://ecobacgiang.vn/150?text=Healthy+Fats+2',
      discount: '-11%',
      name: 'Organic Healthy Fats Item 2',
      rating: 4,
      reviews: 21,
      price: 9,
      originalPrice: 11,
      inStock: 'In Stock',
      category: 'Healthy Fats',
    },
  ];